#! /usr/bin/env python
# -*- coding: UTF-8 -*- vim: et ts=4 sw=4

# The MIT License (MIT)
#
# Copyright (c) 2015 Nicolas Pillot
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the 'Software'),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

import sys
import argparse

# main app
class App:
	def __init__(self):
		# main parser
		top = argparse.ArgumentParser(
			description = 'Fetch and store JCDecaux API results',
		)
		subs = top.add_subparsers()

		# initialize command
		init = subs.add_parser(
			'initialize',
			help = 'create application files',
			description = 'Initialize application'
		)
		init.add_argument(
			'--force',
			action = 'store_true',
			help = 'overwrite existing files'
		)
		init.set_defaults(func=self.initialize)
		# parse arguments
		args = top.parse_args()
		# run specified command
		args.func(args)

	def initialize(self, args):
		print args

# main
if __name__ == '__main__':
	app = App()
